### ISSUE TITLE
Firmware size concern

### ISSUE THREAD

**Issue by kasedy** [rjwats/esp8266-react#103]
I analyzed several big ESP8266 firmware project. All of them at some point faced the issue that firmware doesn't fit into microcontroller memory. Developers had to make optimizations and cut features. Everyone suggest to think beforehand especially about things that hard to change later like core framework or language. I'm a backend developer but I always wanted my IOT devices have modern UI. This project is a great discovery for me. I'm going to use it as a foundation in almost any of my IOT devices. Also I'd like it has manageable size in the future.

Even though react framework is tiny, compiled esp8266-react bundle (BE+FE) takes around 550K. This number will increase if extend it with device specific code. It makes esp8266-react project conditionally usable for ESP-01 microcontrollers with 1M memory. Even if firmware fits in the memory, AOT feature won't work as it requires to have enough free RAM to place new firmware.   Does it make sense to use PRect framework instead of React in order to make firmware footprint even smaller?

I see that several months ago project language was changed to TypeScript. Everyone knows about importance of static code analysis. But It will no longer matter if firmware gets too big to fit into the memory. Do you know if this change reduced the bundle size?

**Comment by rjwats** [comment]
Hi Kasedy,

RAM and firmware size are both a concern and it's all too easy to generate a binary which won't fit comfortably onto the device as you well know. I personally gave up on the 1M variants a while ago.

I had a look at the UI bundle a while ago and there are certainly things that could be done to reduce it's size. The "Roboto" fonts are included (not in hte bundle, but rather in static resources), these are really quite large (45k) so there's an easy win there - but the fonts make it look so pretty and are really the core of Material UI so i've not had the heart to rip them out!

On the TypeScript question, the bundle changed by ~10k IIRC. More likley due to changes I was making at the time and features I added than TypeScript being introduced in particular. While some code is generated by the TypeScript compiler to (support features such as Enums for example), the type erasure means the compiled bundle remains more or less unchanged.

Preact is an intresting question which was raised before, it might be worth looking at. I ran the build through the [bundle analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer) before which was intresting - haven't done that for a while so that could be fun!

Rick
