### ISSUE TITLE
When selecting a network from the scanner hardcoded hostname is applied

### ISSUE THREAD

**Issue by rjwats** [rjwats/esp8266-react#172]
A little change to the mount behaviour here should resolve this:

![image](https://user-images.githubusercontent.com/1330772/86908321-446e3e80-c10e-11ea-9272-0020f28c4846.png)

**Comment by proddy** [comment]
the hostname is still hard-coded though? Could it not somehow take the value from FACTORY_WIFI_HOSTNAME? (I would also argue FACTORY_AP_SSID should be the same and there is only one hostname which is the project name). I'm only raising this point because this on my list of files I need to modify when I fetch a new copy of the library, and the list is getting bigger

**Comment by rjwats** [comment]
The code snippet in the comment above shows the problem, for my reference, not a proposed solution. 

Unless I've missunderstood your comment, I think the PR addresses does address the hard coding by retaining the hostname already configured (using the existing configured hostname):

https://github.com/rjwats/esp8266-react/pull/173/files

**Comment by proddy** [comment]
yup, you're absolutely right. Sorry missed that.
