### ISSUE TITLE
Wifi hostname not set when using static IP

### ISSUE THREAD

**Issue by proddy** [rjwats/esp8266-react#181]
It is still possible to set a Wifi hostname when using a static IP.  I moved the `WiFi.hostname(_state.hostname)` in `WiFiSettingsService::manageSTA()` outside the static_ip condition and it seems to work.

**Comment by rjwats** [comment]
Cool thx

**Comment by rjwats** [comment]
While I'm in this code... do we think it's worthwhile allowing the wifi to be turned off with an "enabled" setting?

I vaguely remember someone asking for such a feature a while ago.

**Comment by proddy** [comment]
can't think of a use case where someone with an ESP wouldn't want to use wifi, unless perhaps as a bluetooth repeater node. without wifi there would be no need for a web server either

**Comment by rjwats** [comment]
Originally that was my thinking too.

However a few people have since indicated that use they access point mode
to configure the device but don't connect it as a station. If the device
has no WiFi network nearby for example. You can effectively disable station
mode by leaving the ssid blank, it just can't be done explicitly at the
moment.

**Comment by proddy** [comment]
oh cool, yes this a good feature. Effectively having an isolated unit not connected to the local wifi. It would mean automatically disabling the NTP, MQTT services too right?
