### ISSUE TITLE
Missing file? Build problem

### ISSUE THREAD

**Issue by tichaonax** [rjwats/esp8266-react#210]
<WWWData.h> referenced from /lib/framework/ESP8266React.h
I do not see this file anymore on your lib but. its referenced and it is making my build fail. It exists locally as a file on my older repos.

![image](https://user-images.githubusercontent.com/1031407/101930918-6462cc00-3b9e-11eb-915c-23e499766cde.png)

![image](https://user-images.githubusercontent.com/1031407/101931066-8f4d2000-3b9e-11eb-99ca-164a62cadaf7.png)

**Comment by rjwats** [comment]
That file is generated by the interface build process (the prebuild python
step triggers this by calling npm). Its its not checked in.

Double check you haven't disabled this in platformio config by mistake.

**Comment by rjwats** [comment]
![image](https://user-images.githubusercontent.com/1330772/101984754-58007100-3c7b-11eb-83b1-feb9564c3b0d.png)

It's this step in the platformio build which creates the WWWData.h file - assuming the NPM process runs successfully on your system.

- Verify this line is present in platformio.ini
- Check the build process has no errors when building the interface with npm

**Comment by rjwats** [comment]
@tichaonax - I'm assuming you resolved your issues here.. re-open the ticket if you need further help.

**Comment by moayyaed** [comment]
I had exactly this issue during build process, the reason is actually that the npm was not built successfully with last commit ( update CRA and other dependencies #274 ).


# My development environments information is :
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22000 N/A Build 22000
npm : 6.14.15
node : v14.18.2
tsc : 4.5.4
# The Solutions that worked with me :

# Step 1:
1- run "npm cache clean --force".  
2- delete the "\interface\node_modules" folder .

# Step 2:
 1.  remove "fsevents": "~2.3.2" from package-lock.json in the following lines:

	Line 5094:         "fsevents": "~2.3.2"
	Line 9431:         "fsevents": "^2.3.2"
	Line 13455:         "fsevents": "^2.3.2"
	Line 13817:         "fsevents": "~2.3.2"
	Line 19837:         "fsevents": "~2.3.2",
	Line 22972:         "fsevents": "^2.3.2",
	Line 25720:         "fsevents": "^2.3.2",
	Line 25997:         "fsevents": "~2.3.2"

 2.  build the project again.

# OR
delete package-lock.json file but take care about incompatible dependencies.
