### ISSUE TITLE
PlatformIO : Espressif32 3.1.0 ambiguous overload for "operator=="

### ISSUE THREAD

**Issue by justoke** [rjwats/esp8266-react#229]
Getting compile errors after updating Platform IO Espressif 32 from 3.0.0 to 3.1.0

![image](https://user-images.githubusercontent.com/26506785/110251178-40354200-7f77-11eb-8ab1-e8e0d78988d8.png)

Likely fix would be to use the toString method on IPAddress like so:

![image](https://user-images.githubusercontent.com/26506785/110251354-fbf67180-7f77-11eb-91e0-0e30308191d3.png)

**Comment by proddy** [comment]
or just type cast e.g. `... settings.dnsIP1 == (IPAddress)INADDR_NONE ....`

**Comment by rjwats** [comment]
Ah yes, I knew this one was coming and probably should have come up with a fix before now. Have pushed a quick fix and dirty fix now...

Perhaps it's best to use a util function rather than the casting or stringifying wherever this particular comparison is done. I'm sure some would suggest inline functions or macros for this sort of thing but I'll raise a PR and we can see what we thing is best.

**Comment by rjwats** [comment]
PR attached with a util for isSet and isNotSet for IPAddress, will test and merge tomorrow if I find no issues.
