### ISSUE TITLE
Disabling MQTT feature causes compiling error.

### ISSUE THREAD

**Issue by FernandoGarcia** [rjwats/esp8266-react#280]
Hi!

Firstly thanks for your great job.

I'm doing some tests using your example and I have noticed that when the MQTT feature is disabled in `features.ini` PIO throw a compiling error. It's expected behaviour or a bug?

![mqtt error](https://user-images.githubusercontent.com/2778501/158230820-5cbae759-7716-4f64-bb43-8e18fe5937f8.png)

Best regards.

**Comment by rjwats** [comment]
This is expected, the demo project is written expecting that feature to be
enabled, I deemed that it would complicate the demo project (backend and
ui) otherwise. You can exclude the feature if your project doesn't use
mqtt, or use the feature flags and the precompiler in your own project
if you want it to be optional.

**Comment by FernandoGarcia** [comment]
Ok, thanks!
